### ISSUE TITLE
Alternative tools

### ISSUE THREAD

**Issue by grawlinson** [sirwart/secrets#4]
Just found a bunch of additional alternatives to add to the README:

* [repo-security-scanner](https://github.com/techjacker/repo-security-scanner)
* [git-secrets](https://github.com/awslabs/git-secrets)

**Comment by sirwart** [comment]
Thanks for sharing those! I was aware of git-secrets but not repo-security-scanner. However I wouldn't want to recommend either based on my understanding of what they do.

git-secrets doesn't come pre-programmed with a set of common secrets except for a few AWS specific ones, so it's going to miss a lot of common secret types unless each user spends time configuring it.

From what I can tell repo-security-scanner is just scanning filenames, not file contents, so it's not technically doing the same thing.

**Comment by grawlinson** [comment]
Fair enough. :)

**Comment by zricethezav** [comment]
👋🏻 I maintain gitleaks which is a comparable tool. Nice work!

https://github.com/zricethezav/gitleaks

**Comment by sirwart** [comment]
@zricethezav I was not aware of gitleaks, just added!

**Comment by magnetophon** [comment]
From [hacker news](https://news.ycombinator.com/item?id=31087508): https://github.com/GitGuardian/ggshield

**Comment by sirwart** [comment]
I took a look at ggshield and decided not to add it since it required an API key to use. I'm not opposed to commercial products but probably not the same class as the other recommended tools.
